# Part 1


## (final) authority

Who has the final authority when it comes to the Great Lakes, is it the US federal government or is the Canadian federal government? Should only the US and Canadian state/provincial governments have a say? Or do the smaller municipalities on the coast deserve the role? 

## Interdependence

Moreover, the natural environment is not predetermined by our arbitrary borders, and the issues that the Great Lakes face extends beyond the coastlines and the natural boundaries of their watershed. I

## Individual vs collective 

 How often, within this current policy climate, do we find one individual making decisions with as widespread of an effect as Tanner's salmon decision without going "unchecked," or receiving input from other voices which will be affected by the issue at hand? 
 
 
## The public 

Egan did mention how the public, after the Cuyahoga River fire of the late 1960s, impacted policy by demanding the federal government did something until Congress passed the Clean Water Act in 1972. After this brief mention of how the general public impacted this issue, I found myself curious whether there were other instances of the public directly influencing the agenda setting process in regard to the policies regarding the upkeep of the Great Lakes. 

